export const ACTIONS = {
  FETCH_ACTIVIDADES: 'FETCH_ACTIVIDADES',
  FETCH_ACTIVIDADES_BY_ID: 'FETCH_ACTIVIDADES_BY_ID',
  FETCH_ACTIVIDADES_BY_PORTAFOLIO_ID: 'FETCH_ACTIVIDADES_BY_PORTAFOLIO_ID',
  CREATE_ACTIVIDADES: 'CREATE_ACTIVIDADES',
  UPDATE_ACTIVIDADES: 'UPDATE_ACTIVIDADES',
  DELETE_ACTIVIDADES: 'DELETE_ACTIVIDADES',

  FETCH_PORTAFOLIOS: 'FETCH_PORTAFOLIOS',
  FETCH_PORTAFOLIOS_BY_ID: 'FETCH_PORTAFOLIOS_BY_ID',
  CREATE_PORTAFOLIOS: 'CREATE_PORTAFOLIOS',
  UPDATE_PORTAFOLIOS: 'UPDATE_PORTAFOLIOS',
  DELETE_PORTAFOLIOS: 'DELETE_PORTAFOLIOS',

  FETCH_USUARIOS: 'FETCH_USUARIOS',
  FETCH_USUARIO_BY_ID: 'FETCH_USUARIO_BY_ID',
  CREATE_USUARIO: 'CREATE_USUARIO',
  UPDATE_USUARIO: 'UPDATE_USUARIO',
  DELETE_USUARIO: 'DELETE_USUARIO',

  FETCH_ACTIVIDADUSUARIOS: 'FETCH_ACTIVIDADUSUARIOS',
  FETCH_ACTIVIDADUSUARIO_BY_ID: 'FETCH_ACTIVIDADUSUARIO_BY_ID',
  CREATE_ACTIVIDADUSUARIO: 'CREATE_ACTIVIDADUSUARIO',
  UPDATE_ACTIVIDADUSUARIO: 'UPDATE_ACTIVIDADUSUARIO',
  DELETE_ACTIVIDADUSUARIO: 'DELETE_ACTIVIDADUSUARIO',
  FETCH_USUARIOS_BY_ACTIVIDAD_ID: 'FETCH_USUARIOS_BY_ACTIVIDAD_ID'
}

export default ACTIONS
