export const ACTIONS = {
    FETCH_ACTIVIDADES: 'FETCH_ACTIVIDADES',
    FETCH_ACTIVIDADES_BY_ID: 'FETCH_ACTIVIDADES_BY_ID',
    FETCH_ACTIVIDADES_BY_PORTAFOLIO_ID: 'FETCH_ACTIVIDADES_BY_PORTAFOLIO_ID',
    CREATE_ACTIVIDADES: 'CREATE_ACTIVIDADES',
    UPDATE_ACTIVIDADES: 'UPDATE_ACTIVIDADES',
    DELETE_ACTIVIDADES: 'DELETE_ACTIVIDADES',
    FETCH_PORTAFOLIOS: 'FETCH_PORTAFOLIOS',
    FETCH_PORTAFOLIOS_BY_ID: 'FETCH_PORTAFOLIOS_BY_ID',
    CREATE_PORTAFOLIOS: 'CREATE_PORTAFOLIOS',
    UPDATE_PORTAFOLIOS: 'UPDATE_PORTAFOLIOS',
    DELETE_PORTAFOLIOS: 'DELETE_PORTAFOLIOS',

}

export default ACTIONS